services:
  cache:
    image: "redis:${CACHE_VERSION:-7.2}-alpine"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    networks:
      - magento
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

networks:
  magento:
